### ISSUE TITLE
update request

### ISSUE THREAD

**Issue by itskekoff** [0x3C50/pyobf2#11]
add different python version compatibility (varCollector)
add string mode to AES encryption
after transformers add transformer to encrypt full code (save imports to pyinstaller)
add flow obfuscation with random code (math, etc.) (#6)
put xortable after imports

**Comment by 0x3C50** [comment]
1. that'll be more effort than its worth, i don't want to remake the assembler
2. sure, added in the next update
3. dynamicCodeObjLauncher exists, that's basically what it does already
4. already done
5. why

**Comment by itskekoff** [comment]
> 1. that'll be more effort than its worth, i don't want to remake the assembler
> 2. sure, added in the next update
> 3. dynamicCodeObjLauncher exists, that's basically what it does already
> 4. already done
> 5. why

1. write in python without assembler (if u can)
5. idk, it will be look good

**Comment by addi00000** [comment]
By assembler he means [this](https://github.com/0x3C50/pyobf2/blob/master/pyobf2/lib/assembler.py) not actual assembly code.

**Comment by 0x3C50** [comment]
> By assembler he means [this](https://github.com/0x3C50/pyobf2/blob/master/pyobf2/lib/assembler.py) not actual assembly code.

both, the assembly itself is also different on 3.10, for example
