### ISSUE TITLE
renamer ruining classes

### ISSUE THREAD

**Issue by Gowixx** [0x3C50/pyobf2#13]
renamer should ignore variables named `self`

**Comment by 0x3C50** [comment]
why? not calling self self is perfectly legal

**Comment by Gowixx** [comment]
Oh, my bad , I thought it wasn't

Also I fixed the rename on arguments, ill push a fix later

**Comment by Gowixx** [comment]
Also, do you have a discord account I can contact you on?

**Comment by 0x3C50** [comment]
0x150#9699
