### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by ThomasClement** [0x3C50/pyobf2#17]
https://arstechnica.com/security/2023/11/developers-targeted-with-malware-that-monitors-their-every-move/

**Comment by 0x3C50** [comment]
"pyobf" is a common name, "pyobfgood" has no affiliation with pyobf2 or the original pyobf. This project does not contain malware or even tracking, and you can verify that yourself by going over the source code in its entirety, including dependencies.

**Comment by 0x3C50** [comment]
In fact, the same article mentions:

> All eight tools used the string “pyobf” as the first five characters in an attempt to mimic genuine obfuscator tools such as pyobf2 [...].
