### ISSUE TITLE
transformer request new mode

### ISSUE THREAD

**Issue by itskekoff** [0x3C50/pyobf2#7]
add to int transformer obfuscation like this:
```python
# before
print(123)
# after
print((~v << 16) | (~va >> 16))

# where v is (~original >> 16), va is (~original << 16)

# also u can add ^ operator.
```

**Comment by 0x3C50** [comment]
![grafik](https://user-images.githubusercontent.com/99053360/217830746-c2f3b38e-87a1-472d-8406-b8ab9f663712.png)
is this adequate
