### ISSUE TITLE
"chararray" mode transformer - integers not filtered

### ISSUE THREAD

**Issue by addi00000** [0x3C50/pyobf2#8]
When using "chararray" mode under the string encoding transformer, integers are not filtered leading to a type error when `list()` is called on the int.

Ex: 

```py
print(13 + 37)
```

```toml
[encodeStrings]
# Encodes strings to make them harder to read
# Enables this transformer
enabled = true
# How to transform the strings
# Mode chararray is best used with the intObfuscator transformer
# Available modes: b64lzma, chararray
mode = "chararray"
```

```bash
  File "/opt/homebrew/lib/python3.11/site-packages/pyobf2/lib/transformers/encodeStringsTransformer.py", line 96, in visit_Constant
    chars = list(val)
            ^^^^^^^^^
TypeError: 'int' object is not iterable
```

**Comment by addi00000** [comment]
I implemented my own fix which just returns untouched value if not string but that fucked up the dynamic code launcher which you probably know better than me.

**Comment by 0x3C50** [comment]
![grafik](https://user-images.githubusercontent.com/99053360/217908702-91c773ac-dee2-4b89-a29a-0be5b0cee8ed.png)
i forgot the fucking type check

**Comment by 0x3C50** [comment]
whats your fix

**Comment by addi00000** [comment]
I was just returning generic visit if not value is string but as I said I had an additional error when using alongside dynamic launcher

**Comment by 0x3C50** [comment]
> I was just returning generic visit if not value is string but as I said I had an additional error when using alongside dynamic launcher

please give me the code i am too lazy
i will fix later

**Comment by 0x3C50** [comment]
fixed in next update, the dynamicCodeObj transformer issue was a problem on my end. forgot a required field on an ast
